apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 192.168.214.140/32
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      stress; cpu, memory limit for container stress'
  creationTimestamp: "2020-01-24T11:17:22Z"
  generateName: limited-hog-5c8d494fc5-
  labels:
    app: limited-hog
    pod-template-hash: 5c8d494fc5
  name: limited-hog-5c8d494fc5-7l8z8
  namespace: low-usage-limit
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: limited-hog-5c8d494fc5
    uid: 145ed88e-4fb4-4774-8fe7-86cb9d505d2d
  resourceVersion: "337724"
  selfLink: /api/v1/namespaces/low-usage-limit/pods/limited-hog-5c8d494fc5-7l8z8
  uid: d0fe2039-6f85-4b0e-8a8e-3e63da833b3c
spec:
  containers:
  - image: vish/stress
    imagePullPolicy: Always
    name: stress
    resources:
      limits:
        cpu: "1"
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-vsbnk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-magenta-node-1
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-vsbnk
    secret:
      defaultMode: 420
      secretName: default-token-vsbnk
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-01-24T11:17:22Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-01-24T11:17:26Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-01-24T11:17:26Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-01-24T11:17:22Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f73ee1451ab9552643fe0411aa23c1adebbdc962cd1eecb50eed9628009a5046
    image: vish/stress:latest
    imageID: docker-pullable://vish/stress@sha256:b6456a3df6db5e063e1783153627947484a3db387be99e49708c70a9a15e7177
    lastState: {}
    name: stress
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-01-24T11:17:25Z"
  hostIP: 172.20.14.154
  phase: Running
  podIP: 192.168.214.140
  podIPs:
  - ip: 192.168.214.140
  qosClass: Burstable
  startTime: "2020-01-24T11:17:22Z"
