apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
    chart: mysql-1.6.2
    heritage: Helm
    release: mysql
  name: mysql
  namespace: default
spec:
  clusterIP: 10.110.24.22
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: mysql
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
